= Installation on Android Studio 2.3 or above

Unfortunately, Android does not provide official packaging system which allows packaging native libraries with header files. But, there is a workaround! Read below.

First, in order to use **libsvgren** one has to use http://tools.android.com/tech-docs/new-build-system/gradle-experimental[Android Experimental gradle bplugin].

Then, in the `build.gradle` file add a link to my bintray maven repository and add dependency on the **libsvgren** AAR package:
....
repositories {
    maven {
        url 'https://dl.bintray.com/igagis/android/'
    }
}
dependencies {
    //...
    compile 'io.github.igagis:libsvgren:+'
}
....

Then, add the following to the end of your `build.gradle`:
....
task extractNDKLibs {
    doLast {
        configurations.compile.each {
            def file = it.absoluteFile
            copy {
                from zipTree(file)
                into "build/"
                include "ndkLibs/**/*"
            }
        }
    }
}
build.dependsOn('extractNDKLibs')
tasks.whenTaskAdded { task ->
    if (task.name.startsWith('compile')) {
        task.dependsOn('extractNDKLibs')
    }
}
....

Also, add include and link paths for compiler and linker for each ABI:
....
model{
    android {
        //...
        ndk {
            //...
            cppFlags.add("-I" + projectDir.getAbsolutePath() + "/build/ndkLibs/include")
            ldLibs.addAll([
                    //...
                    'svgren',
                    //...
                ])
        }
        abis {
            create("armeabi") {
                ldFlags.add("-L" + projectDir.getAbsolutePath() + "/build/ndkLibs/armeabi")
            }
            create("armeabi-v7a") {
                ldFlags.add("-L" + projectDir.getAbsolutePath() + "/build/ndkLibs/armeabi-v7a")
            }
            create("arm64-v8a") {
                ldFlags.add("-L" + projectDir.getAbsolutePath() + "/build/ndkLibs/arm64-v8a")
            }
            create("x86") {
                ldFlags.add("-L" + projectDir.getAbsolutePath() + "/build/ndkLibs/x86")
            }
            create("x86_64") {
                ldFlags.add("-L" + projectDir.getAbsolutePath() + "/build/ndkLibs/x86_64")
            }
            create("mips") {
                ldFlags.add("-L" + projectDir.getAbsolutePath() + "/build/ndkLibs/mips")
            }
            create("mips64") {
                ldFlags.add("-L" + projectDir.getAbsolutePath() + "/build/ndkLibs/mips64")
            }
        }
        //...
    }
}
....

This is it.
