source 'https://github.com/cppfw/cocoapods-repo.git'

project 'svgren/svgren.xcodeproj'

platform :ios, '12.0'

target "svgren" do
  pod 'svgdom', '>= 0.3.61'
  pod 'rasterimage', '>= 0.1.3'
  pod 'veg', '>= 0.1.0'
end
