source 'https://github.com/igagis/cocoapods-repo.git'

project 'svgren/svgren.xcodeproj'

platform :ios, '8.0'

target "svgren" do
  pod 'svgdom', '>= 0.3.17'
  pod 'cairo', '>= 1.15.4.5'
  pod 'png', '>= 1.4.1.4'
end
